#!/bin/bash

# Merge develop into master and get next version number from semantic-release
git merge origin/develop --no-edit -X theirs
npm install --force
unset GITHUB_ACTIONS
unset GITHUB_EVENT_NAME
semantic_release=$(npx --no-install semantic-release --no-ci --dry-run 2>/dev/null)
next_version=$(echo "$semantic_release" | sed -nE 's/.*The next release version is ([0-9]+\.[0-9]+\.[0-9]+).*/v\1/p')

if [ -z "$next_version" ]; then
  exit 1
else
  release_branch="${next_version//.}"
fi

# Set release branch and version as a output and actions variables for later access
echo release_branch="$release_branch" >> "$GITHUB_OUTPUT"

gh variable set NEXT_RELEASE_VERSION --body "$next_version"
gh variable set RELEASE_BRANCH --body "$release_branch"

# Create release branch
echo "The release branch is: $release_branch" 
git checkout -b "$release_branch"
git push origin "$release_branch"
